### ISSUE TITLE
Notifications are not marked as read

### ISSUE THREAD

**Issue by FlorianLudwig** [ovh/manager#3011]
**Describe the bug**
After clicking on a notification it is still marked "unread"

**To Reproduce**
1. OVH publishes some notification
2. Click the notificaitn icon
3. Click on the notification
4. Go back to dashboard
5. notification cound still the same

**Expected behavior**

1. notification should be marked as read
2. open notification in new tab (as the dashboard is so slow to load, going back is a pain)

![image](https://user-images.githubusercontent.com/432263/83007621-39ef5e00-a014-11ea-9917-822fbfcef99e.png)

**Comment by antleblanc** [comment]
Hi @FlorianLudwig!

Thanks for pointing out this issue and sorry about the delay of the response.
A patch has been deployed that fix the issue, so could you please confirm me that it's working on your side?

Thank you!

**Comment by FlorianLudwig** [comment]
@antleblanc Well, I am used to the response time by now :p 

Anyway, it looks fixed now, thanks!

**Comment by FlorianLudwig** [comment]
Hey,

still (or again?) happening.

I marked everything as read:
![Screenshot from 2020-12-11 11-41-55](https://user-images.githubusercontent.com/432263/102234515-a74fd700-3ef1-11eb-8a37-8c8dcf91d26e.png)

A bit later:

![Screenshot from 2020-12-15 16-19-53](https://user-images.githubusercontent.com/432263/102234499-a28b2300-3ef1-11eb-95d3-5581c0277b39.png)

**Comment by Neustradamus** [comment]
@FlorianLudwig: Thanks for this ticket, I have done one recently and it is a duplicate of this because our problem is very very old and always not solved...

Thanks in advance...

**Comment by FlorianLudwig** [comment]
@Neustradamus I agree, it is a bit sad that a simple issue like this is not dealt with in a timely manner.

**Comment by antleblanc** [comment]
Hi @FlorianLudwig!

A patch has recently been deployed. Issue should be now fixed.

Thanks!

**Comment by Neustradamus** [comment]
The problem is not solved one year after the ticket closing...
